# Generated by Django 4.2.30 on 2026-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webappbuild',
            name='apk_url',
            field=models.URLField(blank=True, help_text='Download-URL der fertigen APK'),
        ),
        migrations.AlterField(
            model_name='webappbuild',
            name='app_id',
            field=models.CharField(blank=True, help_text='Bundle-ID z. B. com.meinefirma.meinapp / Bundle ID e.g. com.mycompany.myapp', max_length=100),
        ),
        migrations.AlterField(
            model_name='webappbuild',
            name='app_name',
            field=models.CharField(help_text='App-Name / App name', max_length=100),
        ),
        migrations.AlterField(
            model_name='webappbuild',
            name='icon_url',
            field=models.URLField(blank=True, help_text='App-Icon URL (512×512 PNG) / App icon URL'),
        ),
        migrations.AlterField(
            model_name='webappbuild',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webappbuild',
            name='ipa_url',
            field=models.URLField(blank=True, help_text='Download-URL der fertigen IPA'),
        ),
        migrations.AlterField(
            model_name='webappbuild',
            name='nav_bar',
            field=models.BooleanField(default=False, help_text='Zeige Vor/Zurück-Leiste / Show nav bar'),
        ),
        migrations.AlterField(
            model_name='webappbuild',
            name='splash_url',
            field=models.URLField(blank=True, help_text='Splash-Screen URL / Splash screen URL'),
        ),
        migrations.AlterField(
            model_name='webappbuild',
            name='status_bar_color',
            field=models.CharField(default='#6366f1', help_text='Hex-Farbe / Hex color', max_length=7),
        ),
        migrations.AlterField(
            model_name='webappbuild',
            name='website_url',
            field=models.URLField(help_text='URL der Website / Website URL'),
        ),
    ]
