# Generated by Django 5.2.1 on 2025-06-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='auth_key',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='user',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(unique=True),
        ),
    ]
