# Generated by Django 5.2.1 on 2025-07-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_developer_description_developer_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
