# Generated by Django 5.2.1 on 2025-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_version_checking_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='developer',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='logo',
            field=models.ImageField(blank=True, upload_to='developer_logos/'),
        ),
        migrations.AddField(
            model_name='developer',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='website',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
