# Generated by Django 5.2.1 on 2025-07-09 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_app_category_app_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.app'),
        ),
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.version'),
        ),
        migrations.AlterField(
            model_name='app',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('none', 'Keine Unterkategorie'), ('action', 'Action'), ('adventure', 'Abenteuer'), ('puzzle', 'Puzzle'), ('strategy', 'Strategie'), ('simulation', 'Simulation'), ('arcade', 'Arcade'), ('racing', 'Rennspiele'), ('role_playing', 'Rollenspiele'), ('sports_games', 'Sportspiele'), ('card_games', 'Kartenspiele'), ('board_games', 'Brettspiele'), ('casual_games', 'Casual Spiele')], max_length=50),
        ),
    ]
