# Generated by Django 5.2.1 on 2025-07-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_pushsubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='new_version',
            field=models.BooleanField(default=False),
        ),
    ]
