# Generated by Django 5.2.1 on 2025-07-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_appinfo_appupdate_roadmapitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinfo',
            name='version',
        ),
    ]
