# Generated by Django 5.2.1 on 2026-02-18 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_emailverificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appscreenshot',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='app',
            name='icon_url',
            field=models.URLField(blank=True, help_text='ImgBB oder andere externe Bild-URL'),
        ),
        migrations.AddField(
            model_name='appscreenshot',
            name='image_url',
            field=models.URLField(blank=True, help_text='ImgBB oder andere externe Bild-URL'),
        ),
        migrations.AddField(
            model_name='appscreenshot',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='logo_url',
            field=models.URLField(blank=True, help_text='ImgBB oder andere externe Bild-URL'),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='app_icons/'),
        ),
        migrations.AlterField(
            model_name='appscreenshot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app_screenshots/'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='developer_logos/'),
        ),
    ]
