# Generated by Django 5.2.1 on 2026-07-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_version_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Eigenes Bild für die Benachrichtigung (optional)'),
        ),
    ]
