# Generated by Django 5.2.1 on 2026-07-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_notification_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('update', 'Update'), ('security', 'Sicherheit'), ('system', 'System'), ('general', 'Allgemein')], default='general', max_length=20),
        ),
    ]
