# Generated by Django 5.2.1 on 2026-07-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='last_download_milestone',
            field=models.PositiveIntegerField(default=0, help_text='Höchster bereits benachrichtigter Download-Meilenstein'),
        ),
    ]
