# Generated by Django 5.2.1 on 2025-07-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='daily_digest',
        ),
    ]
