# Generated by Django 5.2.1 on 2026-07-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_notificationsettings_email_marketing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onesignal_player_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onesignal_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
