# Generated by Django 5.2.1 on 2026-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_userprofile_onesignal_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurity',
            name='joel_digitals_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
