"""
Django settings for appstore project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import environ

BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xf2h1hg21d-1k1t_5j&jgpnso_qclrvff(#^g5994y06=ct-s-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = ['jds-appstore.onrender.com',
                 'jds-appstore.de',
                 'localhost',
                 '127.0.0.1',  # Lokaler Host
                 '::1'  # Lokaler Host für IPv6
                 ]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'settings',  # Deine App für Benutzereinstellungen
    'webapp_builder',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'appstore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'store.context_processors.notifications',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'appstore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db(),  # Liest die DATABASE_URL aus der .env Datei
}

# ImgBB Konfiguration
IMGBB_API_KEY = os.environ.get('IMGBB_API_KEY', '')  # Dein ImgBB API Key
IMGBB_ENABLED = bool(IMGBB_API_KEY)

# OneSignal Konfiguration (userbezogene Push-Benachrichtigungen)
ONESIGNAL_APP_ID = os.environ.get('ONESIGNAL_APP_ID', '')
ONESIGNAL_REST_API_KEY = os.environ.get('ONESIGNAL_REST_API_KEY', '')
ONESIGNAL_ENABLED = bool(ONESIGNAL_APP_ID and ONESIGNAL_REST_API_KEY)

SITE_URL = 'https://jds-appstore.de'

# Maximale Bildgröße für ImgBB (in Bytes)
IMGBB_MAX_FILE_SIZE = 32 * 1024 * 1024  # 32MB

# Erlaubte Bildformate
IMGBB_ALLOWED_FORMATS = ['png', 'jpg', 'jpeg', 'gif', 'webp', 'bmp']

SSO_PROVIDER_URL = "https://joel-digitals.de"  # Oder http://127.0.0.1:8001 für lokal
SSO_CLIENT_ID = "UPvOEkSIvIKRbJJCtWDmwRqqFrHFDpvG"
SSO_CLIENT_SECRET = "mEBYKqPlkOSCthqkYhGWVqOLWPAmLIquWTwfakTrqkduBvYB"
SSO_CALLBACK_URL = "https://jds-appstore.de/accounts/register/callback/" 

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CRON_SECRET = os.environ.get('CRON_SECRET', '')

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Falls du statische Dateien im Projektordner hast:
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Falls du collectstatic benutzt (für Deployment)
STATIC_ROOT = BASE_DIR / "staticfiles"

APPSTORE_LOGO_URL = 'https://jds-appstore.onrender.com/static/images/logo.png'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

VAPID_PUBLIC_KEY = "BCU1r9r9eIkwrw5nN9dgrO-6rwILBiDCI6S7-cACic3gXCVap6kzZeS9twkrgbEBUsXzhWXBt070bt_m8k-rQdc"
VAPID_PRIVATE_KEY = "tDmtHLx7xQVZ9NkW8_oXdSneN83jHd8Ew3bG9xkrhik"
VAPID_EMAIL = "mailto:joel-digitals@gmx.de"

#celery settings
# Celery Konfiguration mit Redis statt AMQP
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


EMAIL_BACKEND = "django_mailjet.backends.MailjetBackend"

MAILJET_API_KEY = "c3f43729e477c3cd3a4cfdd51ef6a2ba"
MAILJET_API_SECRET = "c06b2f2787d4a1ee5bf3c9821c8745c4"
EMAIL_HOST_USER = 'no-reply.jds-appstore@joel-digitals.com '  # ersetzen!
DEFAULT_FROM_EMAIL = 'JDS Appstore <no-reply.jds-appstore@joel-digitals.com>'  # ersetzen!